apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper

spec:
  schedule: 30 6 * * 1-5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scraper
              image: registry.home.dennisskoko.com/lunch/api:latest
              command: ['npm', 'run', 'scrape']
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ['ALL']
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: LUNCH_STORAGE_FILE
                  value: /etc/lunch/restaurants.json
              volumeMounts:
                - name: storage
                  mountPath: /etc/lunch
          volumes:
            - name: storage
              nfs:
                server: storage.lan
                path: /mnt/main/services/lunch
